site_name: My Docs
site_name : Fani's Site
site_url : https://azmi-refani.com

theme : 
  name : material
  icon :
    - logo : material/cat
  features : 
    - search.suggest
    - search.highlight
    - content.tabs.link
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.section
    - navigation.expand
    - toc.integrate
    - navigation.top
    - search.suggest
    #- search.highlight
    - search.share

  plugins : 
    - search
    - tags
    - social : 
      - card_layout: default/accent
      - card_layout_options :
        - background-color : "#0FF1CE"

  palette: 
  # Palette toggle for light mode
  - scheme: default
    toggle:
      icon: material/weather-night 
      name: Switch to dark mode

  # Palette toggle for dark mode
  - scheme: slate
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode

  font:
    text: PT Serif

nav : 
  - Home : "index.md"
  - About Me : "about/aboutme.md"
  - Occupation : 
    - Work Experiences : "occupation/work.md"
  - Portfolios : 
    - IT : "portfolio/IT.md"
    - NON-IT : "portfolio/NON-IT.md"
